
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file was automatically generated by create-search-index.
// Do not edit this file.

import { i18n } from '@/i18n.js';

export type SearchIndexItem = {
	id: string;
	path?: string;
	label: string;
	keywords: string[];
	icon?: string;
	children?: SearchIndexItem[];
};

export const searchIndexes: SearchIndexItem[] = [
	{
		id: 'flXd1LC7r',
		children: [
			{
				id: 'hB11H5oul',
				label: i18n.ts.syncDeviceDarkMode,
				keywords: ['sync', 'device', 'dark', 'light', 'mode'],
			},
			{
				id: 'fDbLtIKeo',
				label: i18n.ts.themeForLightMode,
				keywords: ['light', 'theme'],
			},
			{
				id: 'CsSVILKpX',
				label: i18n.ts.themeForDarkMode,
				keywords: ['dark', 'theme'],
			},
			{
				id: '8wcoRp76b',
				label: i18n.ts.setWallpaper,
				keywords: ['wallpaper'],
			},
		],
		label: i18n.ts.theme,
		keywords: ['theme'],
		path: '/settings/theme',
		icon: 'ti ti-palette',
	},
	{
		id: '6fFIRXUww',
		children: [
			{
				id: 'EcwZE7dCl',
				label: i18n.ts.notUseSound,
				keywords: ['mute'],
			},
			{
				id: '9MxYVIf7k',
				label: i18n.ts.useSoundOnlyWhenActive,
				keywords: ['active', 'mute'],
			},
			{
				id: '94afQxKat',
				label: i18n.ts.masterVolume,
				keywords: ['volume', 'master'],
			},
		],
		label: i18n.ts.sounds,
		keywords: ['sounds', i18n.ts._settings.soundsBanner],
		path: '/settings/sounds',
		icon: 'ti ti-music',
	},
	{
		id: '5BjnxMfYV',
		children: [
			{
				id: '75QPEg57v',
				children: [
					{
						id: 'CiHijRkGG',
						label: i18n.ts.changePassword,
						keywords: [],
					},
				],
				label: i18n.ts.password,
				keywords: ['password'],
			},
			{
				id: '2fa',
				children: [
					{
						id: 'qCXM0HtJ7',
						label: i18n.ts.totp,
						keywords: ['totp', 'app', i18n.ts.totpDescription],
					},
					{
						id: '3g1RePuD9',
						label: i18n.ts.securityKeyAndPasskey,
						keywords: ['security', 'key', 'passkey'],
					},
					{
						id: 'pFRud5u8k',
						label: i18n.ts.passwordLessLogin,
						keywords: ['password', 'less', 'key', 'passkey', 'login', 'signin', i18n.ts.passwordLessLoginDescription],
					},
				],
				label: i18n.ts['2fa'],
				keywords: ['2fa'],
			},
		],
		label: i18n.ts.security,
		keywords: ['security', i18n.ts._settings.securityBanner],
		path: '/settings/security',
		icon: 'ti ti-lock',
	},
	{
		id: 'w4L6myH61',
		children: [
			{
				id: 'ru8DrOn3J',
				label: i18n.ts._profile.changeBanner,
				keywords: ['banner', 'change'],
			},
			{
				id: 'CCnD8Apnu',
				label: i18n.ts._profile.changeAvatar,
				keywords: ['avatar', 'icon', 'change'],
			},
			{
				id: 'yFEVCJxFX',
				label: i18n.ts._profile.name,
				keywords: ['name'],
			},
			{
				id: '2O1S5reaB',
				label: i18n.ts._profile.description,
				keywords: ['description', 'bio'],
			},
			{
				id: 'pWi4OLS8g',
				label: i18n.ts.location,
				keywords: ['location', 'locale'],
			},
			{
				id: 'oLO5X6Wtw',
				label: i18n.ts.birthday,
				keywords: ['birthday', 'birthdate', 'age'],
			},
			{
				id: 'm2trKwPgq',
				label: 'Unnamed marker',
				keywords: ['listenbrainz'],
			},
			{
				id: 'kfDZxCDp9',
				label: i18n.ts.language,
				keywords: ['language', 'locale'],
			},
			{
				id: '2z1CeA4m4',
				label: i18n.ts._profile.metadataEdit,
				keywords: ['metadata'],
			},
			{
				id: 'grCWYebrn',
				label: i18n.ts._profile.followedMessage,
				keywords: ['follow', 'message', i18n.ts._profile.followedMessageDescription],
			},
			{
				id: 'bsXEyBwmL',
				label: i18n.ts.reactionAcceptance,
				keywords: ['reaction'],
			},
			{
				id: '2XLhEGQBA',
				children: [
					{
						id: 'eVoViiF3h',
						label: i18n.ts.flagAsCat,
						keywords: ['cat'],
					},
					{
						id: 'tPmOrkctj',
						label: i18n.ts.flagAsBot,
						keywords: ['bot'],
					},
				],
				label: i18n.ts.advancedSettings,
				keywords: [],
			},
			{
				id: 'Ewa9zgaTU',
				label: 'Unnamed marker',
				keywords: ['count', 'update'],
			},
		],
		label: i18n.ts.profile,
		keywords: ['profile'],
		path: '/settings/profile',
		icon: 'ti ti-user',
	},
	{
		id: '2rp9ka5Ht',
		children: [
			{
				id: 'BhAQiHogN',
				label: i18n.ts.makeFollowManuallyApprove,
				keywords: ['follow', 'lock', i18n.ts.lockedAccountInfo],
			},
			{
				id: '4DeWGsPaD',
				label: i18n.ts.autoAcceptFollowed,
				keywords: ['follow', 'auto', 'accept'],
			},
			{
				id: 'w6l20g0ls',
				label: i18n.ts.makeReactionsPublic,
				keywords: ['reaction', 'public', i18n.ts.makeReactionsPublicDescription],
			},
			{
				id: '9CmV0L3AM',
				label: i18n.ts.followingVisibility,
				keywords: ['following', 'visibility'],
			},
			{
				id: 'CKokK1rRW',
				label: i18n.ts.followersVisibility,
				keywords: ['follower', 'visibility'],
			},
			{
				id: 'jGggrdMQS',
				label: i18n.ts.hideOnlineStatus,
				keywords: ['online', 'status', i18n.ts.hideOnlineStatusDescription],
			},
			{
				id: 'dIJb2nEyy',
				label: i18n.ts.noCrawle,
				keywords: ['crawle', 'index', 'search', i18n.ts.noCrawleDescription],
			},
			{
				id: 'znHEMTRF2',
				label: i18n.ts.preventAiLearning,
				keywords: ['crawle', 'ai', i18n.ts.preventAiLearningDescription],
			},
			{
				id: 'wzRoRCmma',
				label: i18n.ts.makeExplorable,
				keywords: ['explore', i18n.ts.makeExplorableDescription],
			},
			{
				id: 'eB8trIWDa',
				children: [
					{
						id: '2mgCSQEcz',
						label: i18n.ts._accountSettings.requireSigninToViewContents,
						keywords: ['login', 'signin'],
					},
					{
						id: '2hCPIiorI',
						label: i18n.ts._accountSettings.makeNotesFollowersOnlyBefore,
						keywords: ['follower', i18n.ts._accountSettings.makeNotesFollowersOnlyBeforeDescription],
					},
					{
						id: '8EcmWfzZO',
						label: i18n.ts._accountSettings.makeNotesHiddenBefore,
						keywords: ['hidden', i18n.ts._accountSettings.makeNotesHiddenBeforeDescription],
					},
				],
				label: i18n.ts.lockdown,
				keywords: ['lockdown'],
			},
		],
		label: i18n.ts.privacy,
		keywords: ['privacy', i18n.ts._settings.privacyBanner],
		path: '/settings/privacy',
		icon: 'ti ti-lock-open',
	},
	{
		id: '3yCAv0IsZ',
		children: [
			{
				id: 'kMJ5laK3n',
				label: i18n.ts.uiLanguage,
				keywords: ['language'],
			},
			{
				id: 'dlKebHH6k',
				label: i18n.ts.overridedDeviceKind,
				keywords: ['device', 'type', 'kind', 'smartphone', 'tablet', 'desktop'],
			},
			{
				id: 'nxvMUir3T',
				label: i18n.ts.showFixedPostForm,
				keywords: ['post', 'form', 'timeline'],
			},
			{
				id: '84MdeDWL1',
				label: i18n.ts.showFixedPostFormInChannel,
				keywords: ['post', 'form', 'timeline', 'channel'],
			},
			{
				id: 'dOig3ye4Z',
				label: i18n.ts.pinnedList,
				keywords: ['pinned', 'list'],
			},
			{
				id: '4huRldNp5',
				label: i18n.ts.enableQuickAddMfmFunction,
				keywords: ['mfm', 'enable', 'show', 'advanced', 'picker', 'form', 'function', 'fn'],
			},
			{
				id: '1x3JNXj8N',
				label: i18n.ts.rememberNoteVisibility,
				keywords: ['remember', 'keep', 'note', 'visibility'],
			},
			{
				id: 'CfAg0Qekq',
				label: i18n.ts.defaultNoteVisibility,
				keywords: ['default', 'note', 'visibility'],
			},
			{
				id: 'tMm9kH9gy',
				children: [
					{
						id: 'hDdVkBFJP',
						label: i18n.ts.collapseRenotes,
						keywords: ['renote', i18n.ts.collapseRenotesDescription],
					},
					{
						id: 'uJJyDABGu',
						label: i18n.ts.showNoteActionsOnlyHover,
						keywords: ['hover', 'show', 'footer', 'action'],
					},
					{
						id: 'ufc2X9voy',
						label: i18n.ts.showClipButtonInNoteFooter,
						keywords: ['footer', 'action', 'clip', 'show'],
					},
					{
						id: '7Jwvu8bK6',
						label: i18n.ts.enableAdvancedMfm,
						keywords: ['mfm', 'enable', 'show', 'advanced'],
					},
					{
						id: 'yb11lSY1G',
						label: i18n.ts.showReactionsCount,
						keywords: ['reaction', 'count', 'show'],
					},
					{
						id: 'fL49Zxe9i',
						label: i18n.ts.loadRawImages,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'quality', 'raw', 'attachment'],
					},
				],
				label: i18n.ts.note,
				keywords: ['note'],
			},
			{
				id: 'bUOs2UKY4',
				children: [
					{
						id: 'c8gA9Xj2a',
						label: i18n.ts.useGroupedNotifications,
						keywords: ['group'],
					},
				],
				label: i18n.ts.notifications,
				keywords: ['notification'],
			},
			{
				id: 'tjGzqy3qa',
				children: [
					{
						id: '3OeHscv45',
						label: i18n.ts.openImageInNewTab,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'new', 'tab'],
					},
					{
						id: 'bFsNusspF',
						label: i18n.ts.useReactionPickerForContextMenu,
						keywords: ['reaction', 'picker', 'contextmenu', 'open'],
					},
					{
						id: '2h3rY1izt',
						label: i18n.ts.enableInfiniteScroll,
						keywords: ['load', 'auto', 'more'],
					},
					{
						id: 'pkK3eeFKm',
						label: i18n.ts.disableStreamingTimeline,
						keywords: ['disable', 'streaming', 'timeline'],
					},
					{
						id: 'y2v7CV9zs',
						label: i18n.ts.alwaysConfirmFollow,
						keywords: ['follow', 'confirm', 'always'],
					},
					{
						id: 'A8a5hcLce',
						label: i18n.ts.confirmWhenRevealingSensitiveMedia,
						keywords: ['sensitive', 'nsfw', 'media', 'image', 'photo', 'picture', 'attachment', 'confirm'],
					},
					{
						id: 'utFrfuW7X',
						label: i18n.ts.confirmOnReact,
						keywords: ['reaction', 'confirm'],
					},
					{
						id: 'kmdsnVIQX',
						label: i18n.ts.keepCw,
						keywords: ['remember', 'keep', 'note', 'cw'],
					},
					{
						id: 'mNRK0pt8L',
						label: i18n.ts.whenServerDisconnected,
						keywords: ['server', 'disconnect', 'reconnect', 'reload', 'streaming'],
					},
					{
						id: 'vE7KeV4U4',
						label: i18n.ts.numberOfPageCache,
						keywords: ['cache', 'page'],
					},
					{
						id: 'eJ2jme16W',
						label: i18n.ts.dataSaver,
						keywords: ['datasaver'],
					},
				],
				label: i18n.ts.behavior,
				keywords: ['behavior'],
			},
			{
				id: 'F3kpUNvSQ',
				children: [
					{
						id: '4bfFRM0UD',
						label: i18n.ts.forceShowAds,
						keywords: ['ad', 'show'],
					},
					{
						id: '2pB0jWBHo',
						label: i18n.ts.hemisphere,
						keywords: [],
					},
					{
						id: 'eIvnR6Xxo',
						label: i18n.ts.additionalEmojiDictionary,
						keywords: ['emoji', 'dictionary', 'additional', 'extra'],
					},
				],
				label: i18n.ts.other,
				keywords: [],
			},
		],
		label: i18n.ts.preferences,
		keywords: ['general', 'preferences', i18n.ts._settings.preferencesBanner],
		path: '/settings/preferences',
		icon: 'ti ti-adjustments',
	},
	{
		id: 'mwkwtw83Y',
		label: i18n.ts.plugins,
		keywords: ['plugin', 'addon', 'extension', i18n.ts._settings.pluginBanner],
		path: '/settings/plugin',
		icon: 'ti ti-plug',
	},
	{
		id: 'F1uK9ssiY',
		children: [
			{
				id: 'msAcN6u3S',
				label: i18n.ts.accountInfo,
				keywords: ['account', 'info'],
			},
			{
				id: 'ts8DgdnZV',
				label: i18n.ts.accountMigration,
				keywords: ['account', 'move', 'migration'],
			},
			{
				id: '4BG7nBECm',
				label: i18n.ts.closeAccount,
				keywords: ['account', 'close', 'delete', i18n.ts._accountDelete.requestAccountDelete],
			},
			{
				id: '2qI6ruPgi',
				label: i18n.ts._accountTruncate.truncateAccount,
				keywords: ['account', 'truncate'],
			},
			{
				id: '3N4CWpYSc',
				label: i18n.ts.experimentalFeatures,
				keywords: ['experimental', 'feature', 'flags'],
			},
			{
				id: 'oUM3jKXvi',
				label: i18n.ts.developer,
				keywords: ['developer', 'mode', 'debug'],
			},
		],
		label: i18n.ts.other,
		keywords: ['other'],
		path: '/settings/other',
		icon: 'ti ti-dots',
	},
	{
		id: '3icEvyv2D',
		children: [
			{
				id: 'lO3uFTkPN',
				children: [
					{
						id: '5JKaXRqyt',
						label: i18n.ts.showMutedWord,
						keywords: ['show'],
					},
				],
				label: i18n.ts.wordMute,
				keywords: ['note', 'word', 'soft', 'mute', 'hide'],
			},
			{
				id: 'fMkjL3dK4',
				label: i18n.ts.hardWordMute,
				keywords: ['note', 'word', 'hard', 'mute', 'hide'],
			},
			{
				id: 'cimSzQXN0',
				label: i18n.ts.instanceMute,
				keywords: ['note', 'server', 'instance', 'host', 'federation', 'mute', 'hide'],
			},
			{
				id: 'gq8rPy3Du',
				label: `${i18n.ts.mutedUsers} (${ i18n.ts.renote })`,
				keywords: ['renote', 'mute', 'hide', 'user'],
			},
			{
				id: 'mh2r7EUbF',
				label: i18n.ts.mutedUsers,
				keywords: ['note', 'mute', 'hide', 'user'],
			},
			{
				id: 'oSNcK9Yni',
				label: i18n.ts.blockedUsers,
				keywords: ['block', 'user'],
			},
		],
		label: i18n.ts.muteAndBlock,
		keywords: ['mute', 'block', i18n.ts._settings.muteAndBlockBanner],
		path: '/settings/mute-block',
		icon: 'ti ti-ban',
	},
	{
		id: '3Tcxw4Fwl',
		children: [
			{
				id: 'iIai9O65I',
				label: i18n.ts.emailAddress,
				keywords: ['email', 'address'],
			},
			{
				id: 'i6cC6oi0m',
				label: i18n.ts.receiveAnnouncementFromInstance,
				keywords: ['announcement', 'email'],
			},
			{
				id: 'C1YTinP11',
				label: i18n.ts.emailNotification,
				keywords: ['notification', 'email'],
			},
		],
		label: i18n.ts.email,
		keywords: ['email'],
		path: '/settings/email',
		icon: 'ti ti-mail',
	},
	{
		id: 'tnYoppRiv',
		children: [
			{
				id: 'cN3dsGNxu',
				label: i18n.ts.usageAmount,
				keywords: ['capacity', 'usage'],
			},
			{
				id: 'rOAOU2P6C',
				label: i18n.ts.statistics,
				keywords: ['statistics', 'usage'],
			},
			{
				id: 'uXGlQXATx',
				label: i18n.ts.uploadFolder,
				keywords: ['default', 'upload', 'folder'],
			},
			{
				id: 'lMg7SI7l6',
				label: i18n.ts.keepOriginalUploading,
				keywords: ['keep', 'original', 'raw', 'upload', i18n.ts.keepOriginalUploadingDescription],
			},
			{
				id: '2cJF0Nwtm',
				label: i18n.ts.keepOriginalFilename,
				keywords: ['keep', 'original', 'filename', i18n.ts.keepOriginalFilenameDescription],
			},
			{
				id: 'm2YPDYBmZ',
				label: i18n.ts.alwaysMarkSensitive,
				keywords: ['always', 'default', 'mark', 'nsfw', 'sensitive', 'media', 'file'],
			},
			{
				id: 'vpc46wK7V',
				label: i18n.ts.enableAutoSensitive,
				keywords: ['auto', 'nsfw', 'sensitive', 'media', 'file', i18n.ts.enableAutoSensitiveDescription],
			},
		],
		label: i18n.ts.drive,
		keywords: ['drive', i18n.ts._settings.driveBanner],
		path: '/settings/drive',
		icon: 'ti ti-cloud',
	},
	{
		id: 'FfZdOs8y',
		label: i18n.ts.deck,
		keywords: ['deck', 'ui'],
		path: '/settings/deck',
		icon: 'ti ti-columns',
	},
	{
		id: 'BlJ2rsw9h',
		children: [
			{
				id: '9bLU1nIjt',
				label: i18n.ts._settings.api,
				keywords: ['api', 'app', 'token', 'accessToken'],
			},
			{
				id: '5VSGOVYR0',
				label: i18n.ts.manage,
				keywords: ['webhook'],
			},
		],
		label: i18n.ts._settings.serviceConnection,
		keywords: ['app', 'service', 'connect', 'webhook', 'api', 'token', i18n.ts._settings.serviceConnectionBanner],
		path: '/settings/connect',
		icon: 'ti ti-link',
	},
	{
		id: 'gtaOSdIJB',
		label: i18n.ts.avatarDecorations,
		keywords: ['avatar', 'icon', 'decoration'],
		path: '/settings/avatar-decoration',
		icon: 'ti ti-sparkles',
	},
	{
		id: 'AqPvMgn3A',
		children: [
			{
				id: '1wtOIwAdm',
				label: i18n.ts.useBlurEffect,
				keywords: ['blur'],
			},
			{
				id: '6fLNMTwNt',
				label: i18n.ts.useBlurEffectForModal,
				keywords: ['blur', 'modal'],
			},
			{
				id: 'E0WXhhRB1',
				label: i18n.ts.highlightSensitiveMedia,
				keywords: ['highlight', 'sensitive', 'nsfw', 'image', 'photo', 'picture', 'media', 'thumbnail'],
			},
			{
				id: '7iZsGkplG',
				label: i18n.ts.squareAvatars,
				keywords: ['avatar', 'icon', 'square'],
			},
			{
				id: 'AfRMcC6IM',
				label: i18n.ts.showAvatarDecorations,
				keywords: ['avatar', 'icon', 'decoration', 'show'],
			},
			{
				id: 'i7aSaEWaT',
				label: i18n.ts.showGapBetweenNotesInTimeline,
				keywords: ['note', 'timeline', 'gap'],
			},
			{
				id: 'knj98Mx84',
				label: i18n.ts.seasonalScreenEffect,
				keywords: ['effect', 'show'],
			},
			{
				id: 'Bzg77rYNd',
				label: i18n.ts.menuStyle,
				keywords: ['menu', 'style', 'popup', 'drawer'],
			},
			{
				id: '7AOZ1ZgDv',
				label: i18n.ts.emojiStyle,
				keywords: ['emoji', 'style', 'native', 'system', 'fluent', 'twemoji'],
			},
			{
				id: 'fDelHUrBi',
				label: i18n.ts.fontSize,
				keywords: ['font', 'size'],
			},
			{
				id: 'siOW5aSwp',
				label: i18n.ts.useSystemFont,
				keywords: ['font', 'system', 'native'],
			},
			{
				id: 's05dHQ1dW',
				children: [
					{
						id: 'zoMbYCvP0',
						label: i18n.ts.reactionsDisplaySize,
						keywords: ['reaction', 'size', 'scale', 'display'],
					},
					{
						id: 'lGFzLnWfB',
						label: i18n.ts.limitWidthOfReaction,
						keywords: ['reaction', 'size', 'scale', 'display', 'width', 'limit'],
					},
					{
						id: '9E0v8VKIY',
						label: i18n.ts.mediaListWithOneImageAppearance,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'list', 'size', 'height'],
					},
					{
						id: 'xB7MPEF4Q',
						label: i18n.ts.instanceTicker,
						keywords: ['ticker', 'information', 'label', 'instance', 'server', 'host', 'federation'],
					},
					{
						id: '7siYCSodm',
						label: i18n.ts.displayOfSensitiveMedia,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility'],
					},
				],
				label: i18n.ts.displayOfNote,
				keywords: ['note', 'display'],
			},
			{
				id: 'uQfyiHMSs',
				children: [
					{
						id: 'y3uTXsSQ6',
						label: i18n.ts.position,
						keywords: ['position'],
					},
					{
						id: 'PILAdkVM',
						label: i18n.ts.stackAxis,
						keywords: ['stack', 'axis', 'direction'],
					},
				],
				label: i18n.ts.notificationDisplay,
				keywords: ['notification', 'display'],
			},
		],
		label: i18n.ts.appearance,
		keywords: ['appearance', i18n.ts._settings.appearanceBanner],
		path: '/settings/appearance',
		icon: 'ti ti-device-desktop',
	},
	{
		id: '330Q4mf8E',
		children: [
			{
				id: 'eGSjUDIKu',
				label: i18n.ts._exportOrImport.allNotes,
				keywords: ['notes'],
			},
			{
				id: 'iMDgUVgRu',
				label: i18n.ts._exportOrImport.favoritedNotes,
				keywords: ['favorite', 'notes'],
			},
			{
				id: '3y6KgkVbT',
				label: i18n.ts._exportOrImport.clips,
				keywords: ['clip', 'notes'],
			},
			{
				id: 'cKiHkj8HE',
				label: i18n.ts._exportOrImport.followingList,
				keywords: ['following', 'users'],
			},
			{
				id: '3zzmQXn0t',
				label: i18n.ts._exportOrImport.userLists,
				keywords: ['user', 'lists'],
			},
			{
				id: '3ZGXcEqWZ',
				label: i18n.ts._exportOrImport.muteList,
				keywords: ['mute', 'users'],
			},
			{
				id: '84oL7B1Dr',
				label: i18n.ts._exportOrImport.blockingList,
				keywords: ['block', 'users'],
			},
			{
				id: 'ckqi48Kbl',
				label: i18n.ts.antennas,
				keywords: ['antennas'],
			},
		],
		label: i18n.ts._settings.accountData,
		keywords: ['import', 'export', 'data', i18n.ts._settings.accountDataBanner],
		path: '/settings/account-data',
		icon: 'ti ti-package',
	},
	{
		id: 'f08Mi1Uwn',
		children: [
			{
				id: 'C5dRH2Ypy',
				label: i18n.ts.reduceUiAnimation,
				keywords: ['animation', 'motion', 'reduce'],
			},
			{
				id: '5mZxz2cru',
				label: i18n.ts.disableShowingAnimatedImages,
				keywords: ['disable', 'animation', 'image', 'photo', 'picture', 'media', 'thumbnail', 'gif'],
			},
			{
				id: 'c0Iy5hL5o',
				label: i18n.ts.enableAnimatedMfm,
				keywords: ['mfm', 'enable', 'show', 'animated'],
			},
			{
				id: '4HYFjs2Nv',
				label: i18n.ts.enableHorizontalSwipe,
				keywords: ['swipe', 'horizontal', 'tab'],
			},
			{
				id: 'kYVJ3SVNq',
				label: i18n.ts.keepScreenOn,
				keywords: ['keep', 'screen', 'display', 'on'],
			},
			{
				id: 'w4Bv0meAt',
				label: i18n.ts.useNativeUIForVideoAudioPlayer,
				keywords: ['native', 'system', 'video', 'audio', 'player', 'media'],
			},
			{
				id: '1fV9WINCQ',
				label: i18n.ts._contextMenu.title,
				keywords: ['contextmenu', 'system', 'native'],
			},
		],
		label: i18n.ts.accessibility,
		keywords: ['accessibility', i18n.ts._settings.accessibilityBanner],
		path: '/settings/accessibility',
		icon: 'ti ti-accessible',
	},
	{
		id: 'temp-settings-timeline',
		children: [
			{
				id: '7Ww2HoYoV',
				label: i18n.ts.__TL_conf.hideLocalTimeLine,
				keywords: ['local', 'timeline', 'hide'],
			},
			{
				id: 'mySasOznP',
				label: i18n.ts.__TL_conf.hideSocialTimeLine,
				keywords: ['social', 'timeline', 'hide'],
			},
			{
				id: 'w2f80EaVn',
				label: i18n.ts.__TL_conf.hideGlobalTimeLine,
				keywords: ['global', 'timeline', 'hide'],
			},
			{
				id: 'ktgUbUsIA',
				label: i18n.ts.__TL_conf.hideLists,
				keywords: ['lists', 'hide'],
			},
			{
				id: '2iBjjkSGm',
				label: i18n.ts.__TL_conf.hideAntennas,
				keywords: ['antennas', 'hide'],
			},
			{
				id: 'iovqIF1oa',
				label: i18n.ts.__TL_conf.hideChannel,
				keywords: ['channel', 'hide'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.disableAll,
		keywords: ['timeline', 'feed', 'view', 'display'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-profile',
		children: [
			{
				id: 'e3JyN0LLD',
				label: i18n.ts._updateCount.updateFollowerCount,
				keywords: ['profile', 'followers', 'count', 'statistics'],
			},
			{
				id: '8iCAS9OIf',
				label: i18n.ts._updateCount.updateFollowCount,
				keywords: ['profile', 'following', 'count', 'statistics'],
			},
			{
				id: 'hWi9LsBcF',
				label: i18n.ts._updateCount.updateNoteCount,
				keywords: ['profile', 'notes', 'posts', 'count', 'statistics'],
			},
			{
				id: 'wfISaHhxA',
				label: 'Unnamed marker',
				keywords: ['profile', 'save', 'update', 'counts'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.profile,
		keywords: ['profile', 'account'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-privacy',
		children: [
			{
				id: 'eSoREzsf8',
				label: i18n.ts.autoRejectFollowRequest,
				keywords: ['follow', 'reject', 'auto'],
			},
			{
				id: 'FfBmQTkTM',
				label: i18n.ts.carefulBot,
				keywords: ['bot', 'careful'],
			},
			{
				id: 'xpK1rat3',
				label: i18n.ts.autoFollowBack,
				keywords: ['follow', 'back', 'auto'],
			},
			{
				id: '2bZIr9B4m',
				label: i18n.ts.hideActivity,
				keywords: ['activity', 'hide'],
			},
			{
				id: 'CaPrnkb2c',
				label: i18n.ts.hideNoteFromOverview,
				keywords: ['note', 'overview', 'hide'],
			},
			{
				id: 'fwTxqMuSZ',
				label: i18n.ts.hidePublicNotes,
				keywords: ['note', 'public', 'hide'],
			},
			{
				id: '889XNlKVf',
				label: i18n.ts.hideHomeNotes,
				keywords: ['note', 'home', 'hide'],
			},
			{
				id: 'EWNVsdJsc',
				label: i18n.ts.hideLocalOnlyNotes,
				keywords: ['note', 'local', 'hide'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.privacy,
		keywords: ['privacy', 'security', 'visibility', 'permission'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-postform',
		children: [
			{
				id: 'lfuWUUh7R',
				label: 'Unnamed marker',
				keywords: ['post', 'form', 'compose'],
			},
			{
				id: 'pbepXUfEv',
				label: i18n.ts.defaultScheduledNoteDeleteTime,
				keywords: ['post', 'form', 'compose'],
			},
			{
				id: 'fZaOUHzvP',
				label: i18n.ts.defaultScheduledNoteDelete,
				keywords: ['post', 'form', 'compose'],
			},
			{
				id: '69hEu5brt',
				label: i18n.ts.textAreaAutoResize,
				keywords: ['post', 'form', 'compose'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.postFormBottomSettingsDescription,
		keywords: ['postform', 'notes', 'posting', 'compose'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-notes',
		children: [
			{
				id: 'kBIgFqOu6',
				label: i18n.ts.directRenote,
				keywords: ['direct', 'renote'],
			},
			{
				id: 'd5nLahEM9',
				label: i18n.ts.hideReactionUsers,
				keywords: ['reaction', 'users', 'hide'],
			},
			{
				id: 'yKt775Z8R',
				label: i18n.ts.enableReactionConfirm,
				keywords: ['reaction', 'confirm'],
			},
			{
				id: 'yi47wF92u',
				label: i18n.ts.enableLikeConfirm,
				keywords: ['like', 'confirm'],
			},
			{
				id: 'xPnWA64cA',
				label: i18n.ts.showInstanceTickerSoftwareName,
				keywords: ['instance', 'ticker', 'software', 'name'],
			},
			{
				id: 'wEuu0zoEW',
				label: i18n.ts.showInstanceTickerVersion,
				keywords: ['instance', 'ticker', 'version'],
			},
			{
				id: 'mxckkvJlg',
				label: i18n.ts.disableNoteNyaize,
				keywords: ['note', 'nyaize', 'disable'],
			},
			{
				id: 'dIopDMc2s',
				label: i18n.ts.hideReactionCount,
				keywords: ['reaction', 'count', 'hide'],
			},
			{
				id: 'Biy6IN3Qt',
				label: i18n.ts.showLikeButton,
				keywords: ['like', 'button', 'show'],
			},
			{
				id: 'kQRjyq3EG',
				label: i18n.ts.selectReaction,
				keywords: ['reaction', 'select'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.like,
		keywords: ['notes', 'posts', 'content', 'display'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-llm',
		children: [
			{
				id: '5aSmPDVN2',
				label: i18n.ts._llm.useGeminiLLMAPI,
				keywords: ['llm', 'gemini', 'api', 'server'],
			},
			{
				id: 'ArCynoaCt',
				label: i18n.ts._llm.useGeminiWithMedia,
				keywords: ['llm', 'gemini', 'media', 'images', 'photos'],
			},
			{
				id: '35qYzAeCB',
				label: i18n.ts._llm.useLlmContentFilter,
				keywords: ['llm', 'content', 'filter', 'inappropriate'],
			},
			{
				id: 'sPhJxRF9c',
				label: i18n.ts._llm.geminiTokenLabel,
				keywords: ['llm', 'gemini', 'token', 'api key'],
			},
			{
				id: 'xqBGe9wp4',
				label: i18n.ts._llm.geminiModelLabel,
				keywords: ['llm', 'gemini', 'model', 'version'],
			},
			{
				id: 'ysMdKlxRl',
				label: i18n.ts._llm.geminiSystemPromptLabel,
				keywords: ['llm', 'gemini', 'system', 'prompt', 'instruction'],
			},
			{
				id: 'vus3Uhqbx',
				label: i18n.ts._llm.geminiSummarizePromptLabel,
				keywords: ['llm', 'gemini', 'note', 'summarize', 'prompt'],
			},
			{
				id: '5PC8njQNA',
				label: i18n.ts._llm.geminiProfileSummarizePromptLabel,
				keywords: ['llm', 'gemini', 'profile', 'summarize', 'prompt'],
			},
			{
				id: 'lkrtyhK8I',
				label: i18n.ts._llm.geminiNoteLongText,
				keywords: ['llm', 'gemini', 'notes', 'long', 'text', 'format'],
			},
			{
				id: 'Iv1ZRYYe',
				label: i18n.ts._llm.geminiNoteShortText,
				keywords: ['llm', 'gemini', 'notes', 'short', 'text', 'format'],
			},
			{
				id: 'zuAVfN4lH',
				label: i18n.ts._llm.geminiNoteSimpleText,
				keywords: ['llm', 'gemini', 'notes', 'simple', 'text', 'format'],
			},
			{
				id: 'hmMlc2Miu',
				label: i18n.ts._llm.geminiNoteCasualText,
				keywords: ['llm', 'gemini', 'notes', 'casual', 'text', 'format'],
			},
			{
				id: 'kQhUokyEN',
				label: i18n.ts._llm.geminiNoteProfessionalText,
				keywords: ['llm', 'gemini', 'notes', 'professional', 'text', 'format'],
			},
			{
				id: 'cue9YHc4d',
				label: i18n.ts._llm.geminiNoteCatText,
				keywords: ['llm', 'gemini', 'notes', 'cat', 'text', 'format'],
			},
			{
				id: 'tHEdmbTS5',
				label: i18n.ts._llm.geminiNoteCustomText,
				keywords: ['llm', 'gemini', 'notes', 'custom', 'text', 'format'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts._llm.title,
		keywords: ['llm', 'ai', 'language model'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-earthquake',
		children: [
			{
				id: '8K6CmTqkf',
				label: i18n.ts._earthquakeWarning.enable,
				keywords: ['earthquake', 'warning', 'enable'],
			},
			{
				id: 'ev3aarKpH',
				label: i18n.ts._earthquakeWarning.intensityThreshold,
				keywords: ['earthquake', 'intensity', 'threshold'],
			},
			{
				id: 'd71v4Qukz',
				label: i18n.ts._earthquakeWarning.notificationStyle,
				keywords: ['earthquake', 'notification', 'display', 'style'],
			},
			{
				id: 'hrShTIyyZ',
				label: i18n.ts._earthquakeWarning.toastDuration,
				keywords: ['earthquake', 'notification', 'duration', 'time'],
			},
			{
				id: 'a2UWiup4A',
				label: i18n.ts._earthquakeWarning.soundEnable,
				keywords: ['earthquake', 'sound', 'enable'],
			},
			{
				id: 'yHP3YtmI8',
				label: i18n.ts._earthquakeWarning.soundType,
				keywords: ['earthquake', 'sound', 'type'],
			},
			{
				id: 'yjyL6kkwP',
				label: i18n.ts._earthquakeWarning.enableTts,
				keywords: ['earthquake', 'tts', 'voice'],
			},
			{
				id: 'l6QtcorM0',
				label: i18n.ts._earthquakeWarning.ttsRate,
				keywords: ['earthquake', 'tts', 'speed', 'rate'],
			},
			{
				id: 'iw26tuvno',
				label: i18n.ts._earthquakeWarning.regionFilterEnable,
				keywords: ['earthquake', 'region', 'filter', 'enable'],
			},
			{
				id: 'BzKX1GBHN',
				label: i18n.ts._earthquakeWarning.throttleTime,
				keywords: ['earthquake', 'notification', 'throttle', 'time'],
			},
			{
				id: 'qdGh5C2F2',
				label: i18n.ts._earthquakeWarning.ignoreTraining,
				keywords: ['earthquake', 'ignore', 'training', 'test'],
			},
			{
				id: 'jvVzZs79S',
				label: i18n.ts._earthquakeWarning.connectionNotify,
				keywords: ['earthquake', 'connection', 'notify'],
			},
			{
				id: 'mu3QqyOKi',
				label: i18n.ts._earthquakeWarning.loggingLevel,
				keywords: ['earthquake', 'log', 'level'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts._earthquakeWarning.clearLogs,
		keywords: ['earthquake', 'alert', 'notification', 'safety'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-drive',
		children: [
			{
				id: 'p10LNaMLQ',
				label: i18n.ts._imageCompressionMode.title,
				keywords: ['drive', 'image', 'compression', 'mode'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: 'Unnamed marker',
		keywords: ['drive'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-behavior',
		children: [
			{
				id: 'mi44y9woD',
				label: i18n.ts._reactionChecksMuting.title,
				keywords: ['reaction', 'muting', 'block', 'ignore', 'notifications'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.behavior,
		keywords: ['behavior', 'interaction', 'actions', 'default'],
		path: '/settings/temp-settings',
	},
	{
		id: 'temp-settings-appearance',
		children: [
			{
				id: '4oTYDPZVA',
				label: i18n.ts.customFont,
				keywords: ['font'],
			},
			{
				id: 'temp-settings-root',
				label: i18n.ts.originalFeature,
				keywords: ['temp', i18n.ts.originalFeature],
				icon: 'ti ti-git-fork',
			},
		],
		label: i18n.ts.appearance,
		keywords: ['appearance', 'theme', 'design', 'layout', 'ui'],
		path: '/settings/temp-settings',
	},
] as const;

export type SearchIndex = typeof searchIndexes;
