#!/bin/bash

echo "=== 複数リアクション機能のテストスクリプト ==="
echo ""
echo "このスクリプトは、複数リアクション機能が正しく動作するかテストします。"
echo ""
echo "1. マイグレーションを実行"
echo "   cd packages/backend && pnpm migration:run"
echo ""
echo "2. APIスキーマを再生成"
echo "   pnpm build-misskey-js-with-types"
echo ""
echo "3. フロントエンドとバックエンドを起動"
echo "   pnpm dev"
echo ""
echo "4. ブラウザでMisskeyにアクセスし、以下をテスト:"
echo "   - ノートに複数の異なるリアクションを付ける"
echo "   - 同じリアクションを2回付けようとするとエラーになることを確認"
echo "   - 特定のリアクションを削除できることを確認"
echo "   - リアクション一覧に自分の複数のリアクションが表示されることを確認"
echo ""
echo "注意: データベースのバックアップを取ることを推奨します。"