name: "Pull Request Labeler"
on:
  pull_request_target:
    branches-ignore:
      - 'l10n_develop'

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
